### ISSUE TITLE
install failed problem

### ISSUE THREAD

**Issue by jiangjiaqi6** [huiscliu/sxamg#1]
Hi,
I want to learn and use the sxamg you developed, but after I type `make install`, there are some errors：

`make[1]: Entering directory '/home/txt/Downloads/sxamg-master/src'`
`make[1]: Nothing to be done for 'default'.`
`make[1]: Leaving directory '/home/txt/Downloads/sxamg-master/src'`
`cp: cannot stat 'lib/libsxamg.a': No such file or directory`
`Makefile:28: recipe for target 'install' failed`
`make: *** [install] Error 1`

Whether I use `./configure, make, sudo make install `or `./configure --prefix/xx/xx, make, make install `will have this problem, the installation directory has only one empty folder lib

**Comment by huiscliu** [comment]
Fixed. Thanks for reporting.
