### ISSUE TITLE
Meaning of the variable 'verb'

### ISSUE THREAD

**Issue by TXTsky** [huiscliu/sxamg#2]
Hi,
     When I was reading your code, I saw a variable `verb`. I'm sorry I didn't understand the function of the variable. Could you please tell me the details of the variable?
For example, in` example/amg.c`
`pars.verb = 3;`

Thanks!

**Comment by huiscliu** [comment]
verb controls how much information will be output during assembling and solution. Higher value means more output. 0 or negative means no output...

**Comment by TXTsky** [comment]
Thanks!
