### ISSUE TITLE
Plugin as a preconditioner

### ISSUE THREAD

**Issue by yangpl** [huiscliu/sxamg#3]
Hi, Dr. Liu,
I like your refactorization software sxamg. I am trying to plugin it to solve a 3D Maxwell equation (complex in frequency domain which has been converted into a rea-valued linear system Ax=bl). Unfortunately, the code runs into AMG setup stage without exist for hours.
I do not know why, because I was able to run your examples of 3D Poisson equation successfully. Can you give me some help?

I think you have made a lot of optimization for sxamg in grid coarsening. But I was unable to figure out what has been implemented exactly. Typically, op-coarsen.c is the one I am looking at. Can you provide a reference or paper which you were following?

Any help would be highly appreciated!

Best regards,
Pengliang

**Comment by huiscliu** [comment]
Hi Pengliang,

Sorry I didn't login for very long time. You may run into a bug, and you may plug some print functions to check which function cause the issue.

Please leave you email here, and I will send you some tutorials.

**Comment by yangpl** [comment]
Hi Dr. Liu,

My email is: pengliang.yang@hit.edu.cn The difficult part for me is an efficient implementation of Ruge-Stuben algorithm for grid point partitioning. In fact I have managed to do it, but the efficiency of my code is poor. Here is my output information for a 3D Poisson equation inversion:
level=0, nrow=2146689, nnz=14926977, nnz_ratio=3.24e-06
allocate at level=1, nrow=1073344, nnz=20094778, nnz_ratio=1.74e-05
allocate at level=2, nrow=403780, nnz=31120280, nnz_ratio=1.91e-04
allocate at level=3, nrow=213222, nnz=29535166, nnz_ratio=6.50e-04
allocate at level=4, nrow=120681, nnz=36384105, nnz_ratio=2.50e-03
allocate at level=5, nrow=70426, nnz=39588596, nnz_ratio=7.98e-03
allocate at level=6, nrow=39252, nnz=33589304, nnz_ratio=2.18e-02
allocate at level=7, nrow=20084, nnz=20645256, nnz_ratio=5.12e-02
allocate at level=8, nrow=9555, nnz=9117241, nnz_ratio=9.99e-02
allocate at level=9, nrow=4633, nnz=3073903, nnz_ratio=1.43e-01
AMG, iter=0 |r|=1.456186e+03
AMG, iter=1 |r|=9.548365e+01
AMG, iter=2 |r|=1.429817e+01
AMG, iter=3 |r|=1.035982e+01
AMG, iter=4 |r|=4.749456e+00
AMG, iter=5 |r|=2.458707e+00
AMG, iter=6 |r|=3.471106e+00
AMG, iter=7 |r|=1.987545e+00
AMG, iter=8 |r|=4.860176e-01
AMG, iter=9 |r|=6.251507e-01
free at level=1
free at level=2
free at level=3
free at level=4
free at level=5
free at level=6
free at level=7
free at level=8
free at level=9
You can see that each level almost take half number of rows from previous level. So it is inefficient. Your code is much more efficient for solving this example problem. If I give parameters which are not good enough, (typically the dimension parameter at the coarsest grid for direct solve of linear system using Gaussian elimination or iterative solver) my AMG fails. Hope for your help!

Best,
Pengliang

**Comment by huiscliu** [comment]
Did you receive my mail?

**Comment by yangpl** [comment]
Yes, I got your email. Thanks for two pdf references.
